# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'background.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 844)
        MainWindow.setMinimumSize(QtCore.QSize(500, 844))
        MainWindow.setMaximumSize(QtCore.QSize(500, 844))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -40, 500, 900))
        self.widget.setMinimumSize(QtCore.QSize(500, 900))
        self.widget.setMaximumSize(QtCore.QSize(500, 900))
        self.widget.setStyleSheet("background-image: url(:/newPrefix/1.png);")
        self.widget.setObjectName("widget")
        self.pred = QtWidgets.QPushButton(self.widget)
        self.pred.setGeometry(QtCore.QRect(120, 510, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pred.setFont(font)
        self.pred.setStyleSheet("background: rgb(0, 151, 178);")
        self.pred.setObjectName("pred")
        self.input = QtWidgets.QPlainTextEdit(self.widget)
        self.input.setGeometry(QtCore.QRect(140, 300, 211, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input.setFont(font)
        self.input.setStyleSheet("background:#fff")
        self.input.setPlainText("")
        self.input.setObjectName("input")
        self.end = QtWidgets.QPushButton(self.widget)
        self.end.setGeometry(QtCore.QRect(280, 510, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.end.setFont(font)
        self.end.setStyleSheet("background:rgb(0, 151, 178)")
        self.end.setObjectName("end")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pred.setText(_translate("MainWindow", "Predict"))
        self.end.setText(_translate("MainWindow", "End"))
import pic_rc
